from enum import Enum

BATTERY_CAPACITY = 13500
BATTERY_FLOOR = 0.05

EFFICIENCY = 0.9

INVERTER_CLIPPING = 4000
TICK_TIME = 15 #Minutes

GRID_CONSTRAINT = 20000

class PRIORITY_OPTIONS(Enum):
    LOAD = 1
    CHARGE = 2
    PRODUCE = 3

CHARGE_PRIORITY = PRIORITY_OPTIONS.LOAD

CLOUD_COVERAGE = 0.3 # 0-1

SIMULATION_DAYS = 1
MINUTES_PER_TICK = 15

SOLAR_PEAK = 5000

BASE_LOAD = 500